### ISSUE TITLE
Unable to export RAVE v2 runs

### ISSUE THREAD

**Issue by scottyeung** [becker929/rave-training#1]
Thanks for creating this almost one-click deploy script, it works like magic. However, when I tried to export the runs I bumped into this issue. What else could've been done to rectify the situation?

ubuntu@192-9-132-119:~$ /home/ubuntu/.pyenv/versions/3.10.11/bin/rave export --run="/home/ubuntu/rave-training/runs/sakamoto-piano_64ca69d341/" --streaming

INFO:root:library loading
INFO:root:DEBUG
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmp72120vf1
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmp72120vf1/_remote_module_non_scriptable.py

I0903 08:45:48.555282 139763641497408 export.py:338] building rave

Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.10.11/bin/rave", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/scripts/main_cli.py", line 34, in main
    app.run(export.main)
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/scripts/export.py", line 340, in main
    gin.parse_config_file(os.path.join(FLAGS.run, "config.gin"))
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gin/config.py", line 2450, in parse_config_file
    includes, imports = parse_config(f, skip_unknown=skip_unknown)
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gin/config.py", line 2338, in parse_config
    with utils.try_with_location(statement.location):
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gin/utils.py", line 60, in try_with_location
    augment_exception_message_and_reraise(exception, _format_location(location))
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gin/utils.py", line 56, in try_with_location
    yield
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gin/config.py", line 2340, in parse_config
    parse_context.process_import(statement)
  File "/home/ubuntu/.pyenv/versions/3.10.11/lib/python3.10/site-packages/gin/config.py", line 205, in process_import
    module = __import__(statement.module, fromlist=fromlist)
ModuleNotFoundError: No module named 'rave.balancer'
  In file "/home/ubuntu/rave-training/runs/sakamoto-piano_64ca69d341/config.gin", line 5
    from rave import balancer

**Comment by becker929** [comment]
Hi thank you for this well-written issue. Looking into it.
